server:
  port: 5000

spring:
  cloud:
    config:
      name: config
      server:
        git:
          uri: https://github.com/francislagueu/tickets-spring
        search-paths: config-files*
  application:
    name: config